[### 오류코드보단 예외를 사용하라
```java
public class DeviceController {
  ...
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    // Check the state of the device
    if (handle != DeviceHandle.INVALID) {
      // Save the device status to the record field
      retrieveDeviceRecord(handle);
      // If not suspended, shut down
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log("Device suspended. Unable to shut down");
      }
    } else {
      logger.log("Invalid handle for: " + DEV1.toString());
    }
  }
  ...
}
```
예외처리 블록 없이 조건문으로 메서드를 호출 하는 방식의 문제점은 호출자의 코드가 복잡해진다.
호출자는 메서드를 호출하는 즉시 발생하는 오류에대해 확인해야 하기 때문이다.

```java
public class DeviceController {
  ...
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }
    
  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);
    pauseDevice(handle); 
    clearDeviceWorkQueue(handle); 
    closeDevice(handle);
  }
  
  private DeviceHandle getHandle(DeviceID id) {
    ...
    throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    ...
  }
  ...
}


```
두 코드 예제에서 저자가 말하는 오류처리와 깨끗한 코드의 연관성을 볼 수있다.
첫번째 코드의 디바이스를 종료하는 부분과 오류처리 알고리즘부분을 나누어 
코드가 깔끔해 졌다.


예외처리를 하지않을 이유는 없다.
우리가 사용하는 프로그램이나 디바이스가 예측하지 못한 입력이
있을 수 있고, 어떤 이유로던 실패할 가능성이 있기 때문이다.




### Try,Catch,Finally

저자는 try 문이 트렌잭션과 유사하다 말한다.
try 블록에 들어가는 코드를 실행하면 어떤 시점이던 실행이 중단된 후 catch 블록으로 넘어가면서
프로그램 실행중에 어떤 일이 생기던 catch 블록은 상태를 일관성있게 유지해야 하기 때문이다.


```java
@Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }
  
  public List<RecordedGrip> retrieveSection(String sectionName) {
    // dummy return until we have a real implementation
    return new ArrayList<RecordedGrip>();
  }
```
위 코드에선 예외를 던지지 않으므로 단위테스트가 실패하므로, 저자는
잘못된 파일 접근을 시도하는 것으로 구현을 변경한다.

```java
public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
      throw new StorageException("retrieval error", e);
    }
  return new ArrayList<RecordedGrip>();
}
```

catch 블록에서 예외 유형을 좁혀 실제 fileInputStream 생성자가 던지는
FileNotFoundException 을 잡아낸다.


```java
public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName);
      stream.close();
    } catch (FileNotFoundException e) {
      throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
  }
```
저자는 강제로 예외를 던지는 테스트 케이스를 작성후
테스트를 통과하게 코드를 작성하는 방법을 권장한다.

잘못된 입력값으로 예외를 던지는 단위테스트를 통해 코드를 리팩터링하면
자연스럽게 try 블록의 트랜잭션 범위부터 구현하게 된다.

### UncheckedException 을 사용하자

checkedException(확인된 예외)은 단일 책임원칙을 위반한다.

```java

import java.io.IOException;

public class SubService {
    public void performAction() throws IOException {
        // 특정 작업 수행
        if (//조건 생략) {
            throw new IOException("IO 오류 발생");
        }
    }
}
```

```java
import java.io.IOException;

public class MidService {
    private SubService subService;

    public MidService(SubService subService) {
        this.subService = subService;
    }

    public void process() throws IOException {
        subService.performAction();
    }
}
```

```java
import java.io.IOException;

public class TopService {
    private MidService midService;

    public TopService(MidService midService) {
        this.midService = midService;
    }

    public void execute() {
        try {
            midService.process();
        } catch (IOException e) {
            // 예외 처리
            System.err.println("예외 처리: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        SubService subService = new SubService();
        MidService midService = new MidService(subService);
        TopService topService = new TopService(midService);

        topService.execute();
    }
}
```
하위 메서드에서 던지는예외에 대한 처리를 하는 catch 블럭이 몇단계 이상 상위 메서드에 있을 경우,
예외를 던지는 메서드와 catch 블럭을 가지고있는 상위메서드 사이에있는 메서드가 선언부에 해당 예외를 정의해야 한다.

이는 하위 시스템의 변경에 전체 시스템이 흔들리는 문제를 야기하며 하위 메서드의 작은 수정에도 큰 영향을 미치게 한다.
개방-폐쇄 원칙은 물론이고 객체의 역할에따라 맞지않는 예외를 정의하게 되면서 SRP (단일 책임 원칙)을 위반한다 

checkedException 은 사용할때 발생하는 이익이 문제를 처리하는 비용과 
얼마나 차이가 나는지 고려해볼 점이며,

만약 비용문제가 더 큰 경우에는 UncheckedException 을 통한 예외처리로
협력관계인 메서드 모두가 예외를 정의할 필요없이, 

RuntimeException 으로 실행환경에서 예외를 처리하는 것이 일반적이라 한다.

### NULL 값은 반환하지말자



```java
public void registerItem(Item item) {
    if (item != null) {
      ItemRegistry registry = peristentStore.getItemRegistry();
      if (registry != null) {
        Item existing = registry.getItem(item.getID());
        if (existing.getBillingPeriod().hasRetailOwner()) {
          existing.register(item);
        }
      }
    }
  }
```
위의 코드에선 peristentStore 가 Null 일 경우에대한 예외를 처리하지 않는다.
만약 NullPointException 예외가 발생했을 경우 해당 하위 메서드를 호출하는 호출자 메서드들은
전부 예외에 대해 정의해야 한다.

저자는 위와 같은 코드는 애플리케이션을 통제 불가능하게 만드는 나쁜코드라 말한다.


```java
  List<Employee> employees = getEmployees();
  if (employees != null) {
    for(Employee e : employees) {
      totalPay += e.getPay();
    }
  }
```
위의 코드는 null 을 반환하는 getEmployees 를 변경해 null 이 아닌 빈 리스트를 반환하는 것으로 변경할 수있다.

```java
 List<Employee> employees = getEmployees();
  for(Employee e : employees) {
    totalPay += e.getPay();
  }
  
  public List<Employee> getEmployees() {
    if( .. there are no employees .. )
      return Collections.emptyList();
    }
}
```
Collections.emptyList() 를 통해 미리 정의된 읽기 전용 리스트를 반환하면
null 에 대한 처리를 할 필요가 사라진다.



null 을 리턴하는 것도 나쁘지만 메서드로 넘기는 것은 더 나쁘다.
null 을 메서드의 파라미터로 넣어야 하는 API 를 사용하는 경우가 아니면 메서드로 넘기지 마라.

일반적으로 대다수의 프로그래밍 언어들은 파라미터로 들어온 null 에 대해 적절한 방법을 제공하지 않는다.
외부 라이브러리도 마찬가지이다. Null 이 인수로 넘어오면 코드에 문제가 있을 확률이 높으므로
저자는 이상적인 방법으로 null 을 파라미터로 받지 못하게 하는 것을 제시하고있다.
